name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 从dockerHub拉取镜像
      run: sudo docker pull yangzhaofeng/d345i_record:1.0.0
    
    - name: 推送到阿里云
      run: |
        sudo docker login --username=${{secrets.ALI_USERNAME}} registry.cn-shanghai.aliyuncs.com --password=${{secrets.ALI_PASSWORD}}
        sudo docker tag yangzhaofeng/d345i_record:1.0.0 registry.cn-shanghai.aliyuncs.com/d345i/d345i:1.0.0
        sudo docker push registry.cn-shanghai.aliyuncs.com/d345i/d345i:1.0.0
