name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 从dockerHub拉取镜像
      run: sudo docker pull pytorch/manylinux-cuda92:latest

    - name: 推送到阿里云
      run: |
        sudo docker login --username=Mr_yang registry.cn-shanghai.aliyuncs.com --password-stdin=13005446052Yzf
        sudo docker tag pytorch/manylinux-cuda92:latest registry.cn-shanghai.aliyuncs.com/fast-lio-sam/pytorch-cuda9:1.0.0
        docker push registry.cn-shanghai.aliyuncs.com/fast-lio-sam/pytorch-cuda9:1.0.0
